name: ads_hace_g3
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas>=1.5.0
  - spacy>=3.5.0
  - nltk>=3.8.0
  - scikit-learn>=1.1.0
  - matplotlib>=3.5.0
  - seaborn>=0.12.0
  - wordcloud>=1.8.0
  - joblib>=1.2.0
  - requests>=2.28.0
  - pip>=22.0
  - pip:
      - tqdm>=4.64.0
